# Generated by Django 4.2.4 on 2023-09-13 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Автор', 'verbose_name_plural': 'Авторы'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-dateCreate',), 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
    ]
